version: '3.8'

services:
  telegram-bot-postgres:
    container_name: telegram-bot-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${TELEGRAM_BOT_PG_NAME}
      POSTGRES_PASSWORD: ${TELEGRAM_BOT_PG_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  telegram-bot-pgadmin:
    container_name: telegram-bot-pgadmin
    image: dpage/pgadmin4:8.6
    environment:
      PGADMIN_DEFAULT_EMAIL: ${TELEGRAM_BOT_PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${TELEGRAM_BOT_PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - telegram-bot-postgres
    restart: unless-stopped

  telegram-bot-firefox:
    image: selenium/standalone-firefox
    hostname: firefox
    privileged: true
    shm_size: 2gb
    container_name: selenium-firefox
    ports:
      - "4445:4444"
      - "7900:7900"
    networks:
      - postgres

  telegram-bot-app:
    image: simakoff/bali-events-bot:latest
    container_name: telegram-bot
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_NAME: ${TELEGRAM_NAME}
      TELEGRAM_BOT_PG_NAME: postgres
      TELEGRAM_BOT_PG_PASSWORD: postgres
    ports:
      - "8083:8083"
    networks:
      - postgres
    depends_on:
      - telegram-bot-postgres
      - telegram-bot-firefox

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
