server:
  port: 8083
  shutdown: graceful

spring:
  main:
    banner-mode: off
  application:
    name: bali-events
  datasource:
    url: jdbc:postgresql://telegram-bot-postgres:5432/postgres
    username: ${TELEGRAM_BOT_PG_NAME}
    password: ${TELEGRAM_BOT_PG_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.zalando.logbook: TRACE
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

com:
  balievent:
    bot:
      token: ${TELEGRAM_TOKEN}
      username: ${TELEGRAM_NAME}
