spring:
  datasource:
    url: jdbc:postgresql://telegram-bot-postgres:5432/postgres
    username: ${TELEGRAM_BOT_PG_NAME}
    password: ${TELEGRAM_BOT_PG_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
webdriver:
  local: false
