server:
  port: 8083
  shutdown: graceful

logging.level:
  org.springframework.orm.jpa.JpaTransactionManager: DEBUG

spring:
  main:
    banner-mode: off
  application:
    name: bali-events
  datasource:
    url: jdbc:postgresql://localhost:5433/bali-events
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: 'true'

logging:
  level:
    org.zalando.logbook: TRACE
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

com:
  balievent:
    bot:
      token: 6781420399:AAHi0vGFUPnh-7wBzC7si7hw1XRQmrNmPzA
      username: BaliEventsCoordinatebot
